name: Hello Test Python Versions

on: push

jobs:
  hello-test-python-versions:
    strategy:
      matrix:
       python-version: ['3.10', '3.11', '3.12']

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code so it can be run by GitHub
        uses: actions/checkout@v4

      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."

      - name: List files in repository
        run: |
          echo "The contents of the repository are:"
          ls ${{ github.workspace }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - run: echo "Python has been set up."

      - name: Run the Python code in helloworld.py
        run: |
          echo "Running Python code"
          python helloworld.py
